# Site settings

title: Dreymar's Big Bag Of Kbd Tricks
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A treasure trove of keyboard wisdom. Layout tips, tricks, modifications and additions await in the Big Bag!  Centered around but not limited to the Colemak layout.
url: "https://dreymar.github.io"    # url: "https://dreymar.colemak.org"
github_username:  DreymaR

links:
  - title: layers
    url: layers-main.html
    sub:
      - title: Overview
        url: layers-main.html
      - title: Colemak[eD]
        url: layers-colemaked.html
      - title: Extend!!!
        url: layers-extend.html
      - title: Extend2+
        url: layers-extend.html#ext2plus
      - title: Dead Keys
        url: layers-main.html#deadkeys
  - title: ergonomy
    url: ergo-mods.html
    sub:
      - title: Angle/Wide
        url: ergo-mods.html#AngleWide
      - title: DH/Curl
        url: ergo-mods.html#CurlDH
      - title: Symbols
        url: ergo-mods.html#symbols
      - title: Modifiers
        url: ergo-mods.html#modifiers
  - title: variants
    url: variants.html
    sub:
      - title: Locales
        url: variants.html#locales
      - title: Scripts
        url: variants.html#scripts
      - title: One-Hand
        url: variants.html#mirror
  - title: learning
    url: learning.html
    sub:
      - title: Training
        url: learning.html#training
      - title: Tarmak
        url: tarmak-intro.html
      - title: Tmk Steps
        url: tarmak.html
      - title: Tmk-DH
        url: tarmak.html#tmk-dh
      - title: Tmk FAQ
        url: tarmak-intro.html#faq
  - title: trickery
    url: typing-tricks.html
    sub:
      - title: Screens
        url: typing-tricks.html#swiping
      - title: Gaming
        url: typing-tricks.html#gaming
      - title: USB-2-USB
        url: typing-tricks.html#usb2usb
      - title: Keycaps
        url: typing-tricks.html#keycaps
      - title: Images
        url: typing-tricks.html#images
  - title: links
    url: links-page.html
    sub:
      - title: Get Out More
        url: links-page.html


# Build settings
theme: minima
plugins:
  - jekyll-feed