# Site settings

title: Dreymar's Big Bag Of Kbd Tricks
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A treasure trove of keyboard wisdom. Layout tips, tricks, modifications and additions await in the Big Bag!  Centered around but not limited to the Colemak layout.
baseurl: "/BigBagKbdTrix"
url: "https://dreymar.github.io"
github_username:  DreymaR

links:
  - title: mappings
    url: /key-mappings
  - title: colemaked
    url: /colemaked
  - title: extend
    url: /extend-layers
  - title: ergonomy
    url: /ergo-mods
  - title: variants
    url: /other-layouts
  - title: trickery
    url: /typing-tricks
  - title: links
    url: /guest-links


# Build settings
theme: minima
plugins:
  - jekyll-feed