# Site settings

title: Dreymar's Big Bag Of Kbd Tricks
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A treasure trove of keyboard wisdom. Layout tips, tricks, modifications and additions await in the Big Bag!  Centered around but not limited to the Colemak layout.
url: "https://dreymar.github.io"
github_username:  DreymaR

links:
  - title: mappings
    url: /key-mappings.html
    sub:
      - title: Colemak[eD]
        url: /colemaked.html
      - title: Extend Layers
        url: /extend-layers.html
  - title: ergonomy
    url: /ergo-mods.html
  - title: variants
    url: /other-layouts.html
  - title: trickery
    url: /typing-tricks.html
  - title: links
    url: /guest-links.html


# Build settings
theme: minima
plugins:
  - jekyll-feed